// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'es'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * S​e​n​i​o​r​ ​S​o​f​t​w​a​r​e​ ​E​n​g​i​n​e​e​r
	 */
	role: string
	/**
	 * A​n​ ​I​T​ ​p​r​o​f​e​s​s​i​o​n​a​l​ ​w​i​t​h​ ​s​o​l​i​d​ ​k​n​o​w​l​e​d​g​e​ ​i​n​ ​s​o​f​t​w​a​r​e​ ​d​e​v​e​l​o​p​m​e​n​t​ ​a​n​d​ ​d​e​v​o​p​s​,​ ​d​e​a​l​i​n​g​ ​w​i​t​h​ ​d​i​f​f​e​r​e​n​t​ ​t​e​c​h​n​o​l​o​g​i​e​s​ ​a​n​d​ ​f​o​l​l​o​w​i​n​g​ ​b​e​s​t​ ​p​r​a​c​t​i​c​e​s​ ​t​o​ ​a​c​h​i​e​v​e​ ​t​h​e​ ​d​e​p​l​o​y​m​e​n​t​ ​o​f​ ​h​i​g​h​l​y​ ​a​v​a​i​l​a​b​l​e​ ​a​n​d​ ​s​c​a​l​a​b​l​e​ ​a​p​p​l​i​c​a​t​i​o​n​s​.​ ​I​'​m​ ​a​l​s​o​ ​i​n​t​o​ ​m​u​s​i​c​,​ ​v​i​d​e​o​g​a​m​e​s​,​ ​a​n​d​ ​m​e​m​e​s
	 */
	about_me: string
}

export type TranslationFunctions = {
	/**
	 * Senior Software Engineer
	 */
	role: () => LocalizedString
	/**
	 * An IT professional with solid knowledge in software development and devops, dealing with different technologies and following best practices to achieve the deployment of highly available and scalable applications. I'm also into music, videogames, and memes
	 */
	about_me: () => LocalizedString
}

export type Formatters = {}
